
title: minimal
email: blog@pettersonabade.com
description: "Este é um minimal blog apenas para mostrar como é o uso dessa ferramenta"
  
baseurl: "/minimal-blog" # the subpath of your site, e.g. /blog
url: "https://pettersonabade.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: minimal_twitter
github_username:  minimal_github

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
#permalink: /:categories/:year/:month/:day/:title
#permalink: /:year/:month/:day/:title
permalink: /:title
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
